/**
 * @fileoverview gRPC-Web generated client stub for Game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: src/proto/game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.Game = require('./game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.Game.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.Game.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Game.CreateGameRequest,
 *   !proto.Game.CreateGameResponse>}
 */
const methodDescriptor_GameService_CreateGame = new grpc.web.MethodDescriptor(
  '/Game.GameService/CreateGame',
  grpc.web.MethodType.UNARY,
  proto.Game.CreateGameRequest,
  proto.Game.CreateGameResponse,
  /**
   * @param {!proto.Game.CreateGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Game.CreateGameResponse.deserializeBinary
);


/**
 * @param {!proto.Game.CreateGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Game.CreateGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Game.CreateGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.Game.GameServiceClient.prototype.createGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Game.GameService/CreateGame',
      request,
      metadata || {},
      methodDescriptor_GameService_CreateGame,
      callback);
};


/**
 * @param {!proto.Game.CreateGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Game.CreateGameResponse>}
 *     Promise that resolves to the response
 */
proto.Game.GameServicePromiseClient.prototype.createGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Game.GameService/CreateGame',
      request,
      metadata || {},
      methodDescriptor_GameService_CreateGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Game.JoinGameRequest,
 *   !proto.Game.JoinGameResponse>}
 */
const methodDescriptor_GameService_JoinGame = new grpc.web.MethodDescriptor(
  '/Game.GameService/JoinGame',
  grpc.web.MethodType.UNARY,
  proto.Game.JoinGameRequest,
  proto.Game.JoinGameResponse,
  /**
   * @param {!proto.Game.JoinGameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Game.JoinGameResponse.deserializeBinary
);


/**
 * @param {!proto.Game.JoinGameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Game.JoinGameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Game.JoinGameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.Game.GameServiceClient.prototype.joinGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame,
      callback);
};


/**
 * @param {!proto.Game.JoinGameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Game.JoinGameResponse>}
 *     Promise that resolves to the response
 */
proto.Game.GameServicePromiseClient.prototype.joinGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame);
};


module.exports = proto.Game;

